### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by Crisium** [mrlund/cordova-mobilepay-appswitch#1]
Hi,

thanks for making this open-source. I am using it and it works just fine. 
but...

We have validation problem. When the Phonegap app receives the success in our application it then sends a call to our services in the cloud that the payment has been completed... but how does the service in cloud know that this is valid payment? The mobilepay sdk states from version 1.8 it is possible to setup a url so the backend (mobilepay) can call this url with a status of the payment. This would solve the problem of validation since this would be a communication from mobilepay to our own sevices in the cloud and not through the phonegap.

Reading some of the documention (from the Android docs):

Set the optional Server Callback URL for server-to-server communication in order to receive instant feedback on current transaction. This enables merchants to react accordingly.

Max 255 characters and it must be an HTTPS:// endpoint

// Create a new payment object (as described in "3. Create your first payment")
Payment payment = new Payment();

// Set the callback URL
payment.setServerCallbackUrl("https://example.com/appswitchstatus");

Is it possible to get this url setup working with your code?

Peter

**Comment by Kezzel** [comment]
Hi Peter

The short answer is no, at least we have not succeeded in doing so. We have been in deep dialog with Danske Bank regarding this issue but they could not find the issue.

In the android log we can log out the callback url just before calling the api method for setting it, but at Danske Bank they simply do not register the callback leaving us blank.

They claim that this is working in other implementations (non hybrid solutions) however they also state that is a new not very used feature of the framework.

The solution is to use their REST api for validation instead, thus when calling your server to get the status of a payment, your server must use the REST api to get the status. This is not as clean as the callback solution, but it works. By the way, we are about to implement this exact setup very shortly:-)

Cheers
Mads

**Comment by mrlund** [comment]
@Kezzel Are you using a modified version of the plugin to test this? Because currently we're not enabling any additional parameters to be passed to call the `setServerCallbackUrl()` method on the Payment instance, but assuming that the SDK supports it, it would be trivial to do so.

**Comment by Kezzel** [comment]
Yes it is a slightly modified version:-)

**Comment by Crisium** [comment]
@mrlund can add the code to support it? 
@Kezzel I haven't tried it, but it seems strange that it doesn't work. I'm thinking perhaps your service needs to whitelist mobilepay. If @mrlund adds support of this optional feature then I will for sure test it.

**Comment by Kezzel** [comment]
Hej callback is send to their server that performs request. Thus it should
not be a whitelist problem in the app. They can be not see the callback at
their end, thus something must go wrong within the appswitch app between
setting the callback and sending the request to their server.

**Comment by mrlund** [comment]
@Kezzel I'm happy to accept a PR with the extensions, if you feel like submitting? 
I agree that whitelist sounds unlikely, and probably the best validation for now is to make a separate request on the orderid returned. That being said, I don't believe there's a significant attack vector here, so unless you're dealing with very high value transactions I wouldn't ben too concerned trusting the appswitch response. IIRC faking the response would require substituting the mobilepay app with a fake, and tricking the appswitch sdk into accepting that would be non-trivial (I'm not a security expert, though!).

**Comment by Kezzel** [comment]
@mrlund The extension we have done is very specific to the project and thus would not make sense to share. The part adding the callback url is pretty simple though.
The real reason for either having the callback or calling the appswitch api for the order status is to cover the situations where there is a network hickup / crash / user closing the app before the response is received in the app. In those case the payment is never registered in your backend, and thus the payment is lost.

**Comment by Crisium** [comment]
@mrlund @Kezzel Mr. Kezzel comment about the payment lost is correct... but I see a more serious problem then just that. Your backend is relying on the "payment success" to come from the app, this is just wrong. The app is just a javascript which anyone can download from the phone and then send the "payment success" directly to the backend. The backend will just accept it even if the user somehow bypassed the mobile-pay part. 

This is why the mobile-pay url is very important. This way the Danish Banks server contacts your backend with the "payment success". Now we are not relying on the "payment success" to come from the app itself, but directly from the Servers that approve it. To avoid others to call my backend "payment success" url directly, I would whitelist the Danish banks server so they are the only ones that are accepted.

If this doesn't make sense.. then I'll draw a diagram when I get home :)

**Comment by mrlund** [comment]
@Crisium I see your point, and you're correct if your concern is not a malicious user tricking your app, but rather tricking the server with a fake transaction. Pending another resolution though, I would go with @Kezzel solution of calling the REST API from your server and validating the transaction. 

I'll try to re-visit this and see if I can get it working, perhaps with a subsequent Mobile Pay SDK update, but it will probably not be in the next month or so.

**Comment by mrlund** [comment]
This seems deliberate from the mobile pay team, since it was removed in the sdk 1.8.1 update: 
https://github.com/MobilePayDev/MobilePay-AppSwitch-SDK/releases

It seems like a nice feature to have, but at this stage it's out of our hands unfortunately.
