### ISSUE TITLE
Not working with build.phonegap.com

### ISSUE THREAD

**Issue by Crisium** [mrlund/cordova-mobilepay-appswitch#2]
When building the iOS version, I get the following error:
"Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-mobilepay-appswitch"

the Android version builds just fine and works.

not much of an error message, so I really do not know what is wrong.

There is a log with the following:

** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/phonegap/Library/Developer/Xcode/DerivedData/TumblingTeamFyn-cenjpzoztlrqqjdwizgxdrzptkhr/Build/Intermediates/ArchiveIntermediates/TumblingTeamFyn/IntermediateBuildFilesPath/TumblingTeamFyn.build/Release-iphoneos/TumblingTeamFyn.build/Objects-normal/armv7/CordovaMobilePayAppSwitch.o TumblingTeamFyn/Plugins/cordova-mobilepay-appswitch/CordovaMobilePayAppSwitch.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/private/tmp/gimlet/2546907/project/cordova/build-release.xcconfig,-workspace,TumblingTeamFyn.xcworkspace,-scheme,TumblingTeamFyn,-configuration,Release,-destination,generic/platform=iOS,-archivePath,TumblingTeamFyn.xcarchive,archive,CONFIGURATION_BUILD_DIR=/private/tmp/gimlet/2546907/project/build/device,SHARED_PRECOMPS_DIR=/private/tmp/gimlet/2546907/project/build/sharedpch

Peter

**Comment by mrlund** [comment]
@Crisium How are you building the app? With xcode or through the cordova command line?

**Comment by Crisium** [comment]
@mrlund I'm using the adobe phonegap build: https://build.phonegap.com/
my private email is: marino.peter@gmail.com .... is it possible to communicate directly with you? I live in Odense.

**Comment by mrlund** [comment]
@Crisium Unless there's sensitive information I prefer to keep the issues on github. I really can't offer one-on-one support for this, I hope you understand. I will try to do a new installation and an iOS build, perhaps over the weekend, and see if I can reproduce the issue.

**Comment by Crisium** [comment]
@mrlund did you get a chance to look into it?
I was thinking of asking you to help solve our problem and we would pay for it. That is why I would like you to contact me. Our app needs to be ready within 1-2 months.

**Comment by mrlund** [comment]
@Crisium The repo is updated with the latest SDK. Could you try removing the plugin and re-installing from the github repo? (it's not updated from the plugin repo yet) 


`cordova plugin add https://github.com/mrlund/cordova-mobilepay-appswitch.git -variable URL_IDENTIFIER="com.example.myapp" --variable URL_SCHEME="myAppUrlScheme" --variable MERCHANT_ID="APPDK0000000000"`

**Comment by Crisium** [comment]
@mrlund I did a rebuild on the adobe server and still got the error.
my config.xml file is what decides what is used and the plugin part looks like this:
<plugin name="cordova-mobilepay-appswitch" spec="https://github.com/mrlund/cordova-mobilepay-appswitch.git">

there is a little more "variables" and end tag.... but the spec attribute is the same  as you updated version, so it is using that.

I still get the error.

**Comment by mrlund** [comment]
@Crisium I think the config got left out there, could you paste it in? Also, I wanted to confirm the error is the same as the original one you posted above, and if you have tried submitting it to phonegap build support?

**Comment by Crisium** [comment]
I have also written on phonegap forum about this (no reply).

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.ttf.skills" version="1.1.1" xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0">
    <name>Tumbling Team Fyn</name>
    <description>
        Springgymnastik og ingen rytme pjat
    </description>
    <author email="marino.peter@gmail.com" href="http://marino.dk">
        Peter Wraae Marino
    </author>
    <content src="index.html" />
    <preference name="orientation" value="portrait" />
	<preference name="android-minSdkVersion" value="23" />
    <icon src="icon.png" />

	<!-- <plugin name="cordova-plugin-uniquedeviceid" source="npm" /> -->
    <plugin name="cordova-plugin-whitelist" spec="1.1.0" />
    <plugin name="cordova-plugin-statusbar" source="npm" spec="~2.1.2" />
    <plugin name="cordova-mobilepay-appswitch" spec="https://github.com/mrlund/cordova-mobilepay-appswitch.git">
        <variable name="URL_IDENTIFIER" value="com.tumblingteamfyn.main" />
        <variable name="URL_SCHEME" value="Info.plist" />
        <variable name="MERCHANT_ID" value="APPDK_SECRET" />
    </plugin>
	
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>

</widget>

```

**Comment by mrlund** [comment]
I'm curious about the values you're using. I assume you're replacing APPDK_SECRET with the real value before build, but what about the `Info.plist` value for the `URl_SCHEME`? I don't know if it would cause this issue, but I doubt it's a valid value for `urlScheme`.

**Comment by Crisium** [comment]
yes. I'm using the correct value for APPDK_SECRET... the Info.plist is created on the adobe build side so I don't have access to it. This is the same file I use for android and the build works and runs fine for android, so I would assume these values are correct.

**Comment by mrlund** [comment]
The urlScheme is only used on ios, and should be a unique value for your app. It's used by the appswitch sdk to return control to your app. 

As I said I don't know if this would cause the issue, but certainly `Info.plist` is not a valid value.

**Comment by mrlund** [comment]
I believe the issue is caused by the included binaries in the AppSwitch SDK, which seems to not be allowed by PhoneGap Build. I don't think there's anything more to be done from this side.
